CREATE TABLE [dbo].[Address]
(
	AddressId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	UserId INT NOT NULL REFERENCES [User](UserId),
	AddressType NVARCHAR(50) NULL,
	Street1 NVARCHAR(MAX) NULL,
	Street2 NVARCHAR(MAX) NULL,
	City NVARCHAR(200) NULL,
	State NVARCHAR(200) NULL,
	Zip NVARCHAR(50),
)
